print("Starting with term frequencies")
Sys.sleep(10)
source("C:/Users/lukas/Documents/GitHub/DSP_Sentiment_Covid/Code/Twitter Descriptive/term_freq_daily_updater.R")
print("Starting with summary stats")
Sys.sleep(10)
source("C:/Users/lukas/Documents/GitHub/DSP_Sentiment_Covid/Code/Twitter Descriptive/sum_stats_daily_updater.R")
print("Starting with df joining")
Sys.sleep(10)
source("C:/Users/lukas/Documents/GitHub/DSP_Sentiment_Covid/Code/Twitter Descriptive/cleaned_raw_sentiment_joiner_daily_update.R")